### PR TITLE
support PEP484 function argument annotation

### PR DESCRIPTION
**Pull request by d2207197**

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for the work here @d2207197 

This would need to pass existing tests (currently you're failing due to Python 2 failures) and also add new tests verifying that this works in all reasonable cases.

**Comment by d2207197** [comment]
my bad.
created accidentally

**Comment by d2207197** [comment]
- passed all existing tests
- added test for function annotation in `tests/test_dispatcher_3only.py`

**Comment by mrocklin** [comment]
I'm glad to see this.  I hope you don't mind but I added a commit with a couple of tests here.  It looks like this doesn't yet work as expected with methods?  Any thoughts on how best to address this?

**Comment by d2207197** [comment]
@mrocklin 
Thanks for adding those tests.  I've updated, and now it works with methods.

**Comment by mrocklin** [comment]
This looks good to me.  CC'ing @oubiwann and @jlowin who have attempted this before to see if they have time to review.

**Comment by jlowin** [comment]
Wow, 2.5 years since #4 -- I think that was back when we were all trying to figure out the "right" way to handle annotations! I think these days we know that method in this PR IS the right way (`inspect.signature` and `parameter.annotation`).

One suggestion is to add a test almost identical to `test_overlaps()` but where the dispatch signature and the annotation signature disagree. The expected behavior is that dispatch is checked first and annotations are only checked if dispatch has no signature provided. Adding a test for that would ensure that the behavior doesn't get changed inadvertently in the future (for example, one day the annotations might be checked first and the dispatch signature would be used to override them).

**Comment by d2207197** [comment]
Thanks for the suggestion. I added the test case.

**Comment by d2207197** [comment]
Is this PR ready to be merged in?

**Comment by mrocklin** [comment]
I apologize for letting this linger.  My inbox has become increasingly less organized/managed recently.

cc'ing @llllllllll in case he wants to take a look

**Comment by d2207197** [comment]
Hi @mrocklin 
Is there anything else I can do for this PR?

**Comment by mrocklin** [comment]
Sure.  Looks good.  I apologize again for my poor response on this.

Thank you so much for implementing this.  I suspect that many people will appreciate it.

**Pull request merged**
