### PR TITLE
Tests - use nose's assert_raises helper

### PR DESCRIPTION
**Pull request by adamchainz**
No need for multipledispatch.utils to define its own when Nose provides ;)

### CODE REVIEW

**Comment by mrocklin** [comment]
Does nose.raises work with pytest as well?

**Comment by adamchainz** [comment]
`pytest.raises` exists on pytest. Happy to move to pytest!

**Comment by mrocklin** [comment]
I guess the advantage of leaving things the way they are is that people can use whichever they prefer, we don't have a testing dependency.

**Comment by mrocklin** [comment]
`raises` is simple enough that I don't perceive a huge win by depending on an external implementation.

**Comment by adamchainz** [comment]
Imho there's no point avoiding testing dependencies. It'd be neatest if there was a tox.ini for testing on all versions of Python and automating all the environment setup.

**Comment by mrocklin** [comment]
I don't have a strong preference one way or the other about tox.  Seems fine to me to include an ini file.

I do see a small value to avoiding testing dependencies, especially with bare, dependency-free, libraries like `multipledispatch`.  I don't yet see a significant value to removing the `raises` utility function other than aesthetics.

**Pull request closed without merging**
